name: small-body
services:
  mpc:
   image: small-body:latest
   build:
     context: .
     dockerfile: docker/Dockerfile
     target: base
     args:
       PYTHON_VERSION: "3.12"
       CUDA_VERSION: "13"
       #UNAME: ${USER}
       #UID: ${DOCKER_UID:-1001}
       #GID: ${DOCKER_GID:-1001}
   stdin_open: true
   tty: true
   network_mode: host
   ipc: host
   privileged: True
   environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     #- XAUTHORITY=/home/${USER}/.Xauthority
   deploy:
     resources:
       reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    #- ~/.Xauthority:/home/${USER}/.Xauthority:rw
    - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    #- ./src:/workspace/src/
    - ./:/workspace/
   command: /bin/bash
